site_name: Web Contracter
docs_dir: docs       
site_dir: docs_public      
theme:
  name: material   

plugins:
  - search
  - api-autonav:
      modules: ["src"]
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google  
            show_source: true
