[mypy]
python_version = 3.11
warn_return_any = False
warn_unused_configs = True
ignore_missing_imports = True
disable_error_code = attr-defined, assignment, arg-type, no-any-return, misc, annotation-unchecked, index, override, call-arg, var-annotated, list-item, return-value

