"""Default configuration values — edit directly in this file."""

CONFIG: dict = {
    "log_level": "INFO",
    "email": {
        "signature": "\n\nBest regards,\nManas Doshi,\nFuture Forwards - https://man27.netlify.app/services",
        "smtp_server": "smtp.gmail.com",
        "smtp_port": 587,
    },
    "email_discovery": {
        "common_prefixes": ["info", "contact", "hello", "support", "admin"]
    },
    "pipeline": {"defaults": {"max_queries": 20, "audit_limit": 20, "email_limit": 20}},
    "timeouts": {
        "connection_test_seconds": 5,
        "http_request_seconds": 15,
        "page_fetch_seconds": 15,
        "email_scrape_seconds": 10,
    },
    "llm": {
        "timeout_seconds": 30,
        "max_retries": 3,
        # "groq": {"model": "llama-3.3-70b-versatile"},
        # "openrouter": {"model": "google/gemma-2-9b-it:free"},
        # "anthropic": {"model": "claude-sonnet-4-6"},
        # "gemini": {"model": "gemini-2.0-flash"},

        "ollama": {
            "model": "llama3.2:latest",
            "base_url": "http://localhost:11434",
        },
        "lm_studio": {
            "model": "local-model",
            "base_url": "http://localhost:1234/v1",
            "api_key": "",
        },
    },
    "scraper": {
        "headless": True,
        "verify_ssl": True,
        "page_load_timeout_ms": 5000,
        "search_wait_timeout_ms": 10000,
        "result_click_delay_ms": 2000,
        "user_agents": [
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0",
        ],
    },
    "qualification": {
        "score_threshold": 90,
        "email_generation_limit": 20,
        "email_max_retries": 3,
    },
    "query_management": {"stale_threshold": 3, "stale_cleanup_days": 30},
    "parallel": {"max_workers": 3, "timeout_per_source_seconds": 30},
    "geographic_focus": {
        "tier_1_metros": {
            "tier": "Tier-1",
            "cities": [
                "Mumbai",
                "Delhi",
                "Bangalore",
                "Chennai",
                "Kolkata",
                "Hyderabad",
                "Pune",
            ],
            "priority": 1,
        },
        "tier_2_cities": {
            "tier": "Tier-2",
            "cities": [
                "Ahmedabad",
                "Jaipur",
                "Lucknow",
                "Indore",
                "Surat",
                "Nagpur",
                "Bhopal",
            ],
            "priority": 2,
        },
        "gujarat_state": {
            "tier": "State-wide",
            "cities": ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Gandhinagar"],
            "priority": 3,
        },
        "business_districts": {
            "tier": "Business Districts",
            "cities": [
                "Bandra-Mumbai",
                "Connaught Place-Delhi",
                "MG Road-Bangalore",
                "Banjara Hills-Hyderabad",
            ],
            "priority": 1,
        },
    },
    "discovery_sources": {
        "sources": {
            "google_maps": {
                "enabled": True,
                "priority": 2,
                "max_results": 50,
                "description": "Google Maps business listings",
            },
            "google_search": {
                "enabled": True,
                "priority": 1,
                "max_results": 50,
                "description": "Google Search for blog/platform websites",
            },
            # "justdial": {
            #     "enabled": True,
            #     "priority": 3,
            #     "max_results": 50,
            #     "description": "JustDial Indian business directory",
            # },
            # "sulekha": {
            #     "enabled": True,
            #     "priority": 5,
            #     "max_results": 50,
            #     "description": "Sulekha Indian community network",
            # },
            # "yellowpages": {
            #     "enabled": True,
            #     "priority": 4,
            #     "max_results": 50,
            #     "description": "YellowPages India",
            # },
            "blogspot": {
                "enabled": True,
                "priority": 1,
                "max_results": 50,
                "description": "Blogspot/Blogger sites",
            },
            "wordpress": {
                "enabled": True,
                "priority": 1,
                "max_results": 50,
                "description": "WordPress.com sites",
            },
            # "wix": {
            #     "enabled": True,
            #     "priority": 1,
            #     "max_results": 50,
            #     "description": "Wix-hosted sites",
            # },
            "website_filter": {
                "enabled": True,
                "priority": 1,
                "max_results": 50,
                "description": "Broad website discovery with TLD filters",
            },
        }
    },
    "discovery_limits": {
        "max_queries_per_run": 500,
        "max_patterns_per_bucket": 30,
        "max_cities_per_segment": 20,
        "max_results_per_query": 50,
        "max_leads_per_query": 20,
    },
    "anti_detection": {
        "enable_throttling": True,
        "throttle_config": {
            "min_delay_ms": 1000,
            "max_delay_ms": 3000,
            "delay_between_queries_ms": 2000,
        },
        "enable_captcha_detection": True,
        "block_patterns": [
            "captcha",
            "verify you are human",
            "access denied",
            "blocked",
            "unusual traffic",
            "rate limit exceeded",
        ],
    },
    "query_scoring": {
        "enabled": True,
        "min_score_threshold": 0.3,
        "llm_scoring": True,
        "historical_weight": 0.6,
        "llm_weight": 0.4,
        "factors": {
            "specificity": 0.3,
            "commercial_intent": 0.3,
            "location_specific": 0.2,
            "competition_level": 0.2,
        },
    },
    "query_performance": {
        "enabled": True,
        "max_consecutive_failures": 3,
        "auto_disable_stale": True,
        "review_stale_interval_days": 7,
    },
    "agents": {
        "execution_order": ["content", "business", "technical", "performance"],
        "weights": {
            "content": 0.3,
            "business": 0.3,
            "technical": 0.25,
            "performance": 0.15,
        },
        "content": {
            "enabled": True,
            "weight": 0.3,
            "timeout": 30,
            "system_message": "You are a brutally honest website content auditor. Score 0-100. Output ONLY JSON.",
            "prompt_template": 'Analyze {bucket} website for \'{business_name}\'.\n\nContent:\n{content}\n\nCheck: value prop clarity, CTAs, tone, trust signals, content quality.\n\nReturn ONLY JSON:\n{{\n  "content_score": 0-100,\n  "observations": [{{"type": "value_proposition|cta|tone|trust|content_quality", "severity": "critical|warning|info", "description": "finding", "recommendation": "fix"}}]\n}}',
        },
        "business": {
            "enabled": True,
            "weight": 0.3,
            "timeout": 30,
            "llm_audit": {
                "enabled": True,
                "system_message": "You are a brutally honest business strategy expert. Score 0-100. Be critical. Output ONLY JSON.",
                "prompt_template": 'Evaluate {bucket} website for \'{business_name}\'.\n\nContent:\n{content}\n\nCheck: service clarity, target audience, differentiation, industry standards.\n\nReturn ONLY JSON:\n{{\n  "business_score": 0-100,\n  "observations": [{{"type": "service_clarity|target_audience|differentiation|standards", "severity": "critical|warning|info", "description": "finding", "recommendation": "fix"}}]\n}}',
            },
            "bucket_overrides": {
                "Developers": [
                    {
                        "id": "dev_github_link",
                        "type": "link_match",
                        "patterns": ["github.com", "gitlab.com", "bitbucket.org"],
                        "description": "No link to code repository",
                        "remediation": "Add a link to your GitHub or code portfolio",
                        "severity": "warning",
                        "score_impact": 10,
                    },
                    {
                        "id": "dev_projects_showcase",
                        "type": "text_match",
                        "patterns": ["projects", "portfolio", "case studies", "work"],
                        "description": "No projects or portfolio section visible",
                        "remediation": "Add a projects or portfolio section",
                        "severity": "critical",
                        "score_impact": 20,
                    },
                    {
                        "id": "dev_skills_section",
                        "type": "text_match",
                        "patterns": [
                            "skills",
                            "technologies",
                            "tech stack",
                            "languages",
                        ],
                        "description": "No skills or technologies section",
                        "remediation": "Add a skills/technologies section",
                        "severity": "warning",
                        "score_impact": 10,
                    },
                ],
                "Marketing Agencies": [
                    {
                        "id": "agency_case_studies",
                        "type": "text_match",
                        "patterns": [
                            "case studies",
                            "success stories",
                            "results",
                            "portfolio",
                        ],
                        "description": "No case studies or results showcase",
                        "remediation": "Add case studies demonstrating client results",
                        "severity": "critical",
                        "score_impact": 20,
                    },
                    {
                        "id": "agency_testimonials",
                        "type": "text_match",
                        "patterns": ["testimonial", "review", "client feedback"],
                        "description": "No client testimonials visible",
                        "remediation": "Add client testimonials and reviews",
                        "severity": "warning",
                        "score_impact": 10,
                    },
                    {
                        "id": "agency_services_clear",
                        "type": "text_match",
                        "patterns": [
                            "services",
                            "what we do",
                            "offerings",
                            "solutions",
                        ],
                        "description": "Services not clearly defined",
                        "remediation": "Create a clear services page",
                        "severity": "warning",
                        "score_impact": 10,
                    },
                ],
                "E-commerce": [
                    {
                        "id": "ecommerce_product_catalog",
                        "type": "text_match",
                        "patterns": ["products", "shop", "catalog", "collection"],
                        "description": "No product catalog visible",
                        "remediation": "Add a clear product catalog or shop section",
                        "severity": "critical",
                        "score_impact": 25,
                    },
                    {
                        "id": "ecommerce_cart_checkout",
                        "type": "link_match",
                        "patterns": ["cart", "checkout", "add to cart", "buy now"],
                        "description": "No shopping cart or checkout",
                        "remediation": "Implement shopping cart and checkout",
                        "severity": "critical",
                        "score_impact": 25,
                    },
                    {
                        "id": "ecommerce_secure_payment",
                        "type": "text_match",
                        "patterns": [
                            "secure payment",
                            "ssl",
                            "encrypted",
                            "payment methods",
                        ],
                        "description": "No mention of secure payment options",
                        "remediation": "Display trust badges and secure payment info",
                        "severity": "warning",
                        "score_impact": 15,
                    },
                ],
                "Restaurants": [
                    {
                        "id": "restaurant_menu",
                        "type": "text_match",
                        "patterns": ["menu", "our dishes", "food", "cuisine"],
                        "description": "No menu visible on website",
                        "remediation": "Add a clear menu with prices and descriptions",
                        "severity": "critical",
                        "score_impact": 20,
                    },
                    {
                        "id": "restaurant_location_hours",
                        "type": "text_match",
                        "patterns": ["hours", "open", "location", "address", "contact"],
                        "description": "Missing location or hours",
                        "remediation": "Add clear location, hours, and contact info",
                        "severity": "critical",
                        "score_impact": 20,
                    },
                    {
                        "id": "restaurant_reservation",
                        "type": "link_match",
                        "patterns": [
                            "reserve",
                            "booking",
                            "reservation",
                            "order online",
                        ],
                        "description": "No online reservation or ordering",
                        "remediation": "Add online reservation or ordering capability",
                        "severity": "warning",
                        "score_impact": 10,
                    },
                ],
                "Photographers": [
                    {
                        "id": "photographer_portfolio",
                        "type": "text_match",
                        "patterns": [
                            "portfolio",
                            "gallery",
                            "work",
                            "photos",
                            "shoots",
                        ],
                        "description": "No portfolio or gallery visible",
                        "remediation": "Add a portfolio gallery showcasing your best work",
                        "severity": "critical",
                        "score_impact": 25,
                    },
                    {
                        "id": "photographer_services",
                        "type": "text_match",
                        "patterns": ["services", "packages", "pricing", "sessions"],
                        "description": "No services or pricing information",
                        "remediation": "Add services and pricing packages",
                        "severity": "warning",
                        "score_impact": 10,
                    },
                    {
                        "id": "photographer_contact_booking",
                        "type": "link_match",
                        "patterns": ["contact", "book", "inquire", "hire"],
                        "description": "No clear contact or booking method",
                        "remediation": "Add clear contact form or booking system",
                        "severity": "warning",
                        "score_impact": 10,
                    },
                ],
                "default": [
                    {
                        "id": "general_services_clear",
                        "type": "text_match",
                        "patterns": ["services", "what we do", "offerings", "products"],
                        "description": "Services or products not clearly defined",
                        "remediation": "Clearly state what you offer",
                        "severity": "warning",
                        "score_impact": 10,
                    },
                    {
                        "id": "general_contact_info",
                        "type": "text_match",
                        "patterns": ["contact", "email", "phone", "address"],
                        "description": "Contact information not easily visible",
                        "remediation": "Make contact information prominent",
                        "severity": "warning",
                        "score_impact": 10,
                    },
                ],
            },
        },
        "technical": {
            "enabled": True,
            "weight": 0.25,
            "timeout": 30,
            "checks": {
                "check_robots_txt": False,
                "title_missing_penalty": 20,
                "title_long_penalty": 5,
                "description_missing_penalty": 15,
                "description_long_penalty": 5,
                "og_missing_penalty": 10,
                "og_incomplete_penalty": 5,
                "viewport_missing_penalty": 20,
                "canonical_missing_penalty": 5,
                "structured_data_missing_penalty": 10,
                "robots_txt_missing_penalty": 5,
                "h1_missing_penalty": 10,
                "h1_multiple_penalty": 5,
                "alt_text_missing_penalty": 10,
                "https_missing_penalty": 20,
            },
            "early_exit_rules": {"max_critical_issues": 2},
        },
        "performance": {
            "enabled": True,
            "weight": 0.15,
            "timeout": 30,
            "thresholds": {
                "max_html_size_kb": 100,
                "max_inline_css_kb": 50,
                "max_inline_js_kb": 50,
                "max_resources": 50,
                "max_response_time_ms": 1000,
            },
        },
    },
    "email_generation": {
        "enabled": True,
        "timeout": 30,
        "system_message": "Write a personalized B2B cold email. Output ONLY valid JSON.",
        "prompt_template": 'Write a cold email for {business_name} ({bucket}).\n\nAudit findings:\n{issue_summary}\n\nRequirements:\n- Mention 1 specific site detail\n- Highlight 1-2 critical issues (design/speed/mobile)\n- Show business impact (lost revenue)\n- Offer free audit/call\n- Max 120 words, no placeholders, no signature\n\nReturn ONLY JSON: {{"subject": "...", "body": "..."}}',
    },
}
